language: python
python:
  - 3.7.3
cache: pip
install:
  - pip install flask
  - pip install pymysql
  - pip install selenium
services:
  - mysql8.0.1
env:
  - MYSQL_HOST=127.0.0.1 MYSQL_USER=root
before_install:
  - mysql -u dev --password="" < SATT-github.sql
script:
  - python testsuit.py
